.TH XCOL 1 xcol\-VERSION
.SH NAME
xcol \- a simple color-picker utility for Xorg
.SH SYNOPSIS
.B xcol
[\fB\-h\fR]
.SH DESCRIPTION
.B xcol
is a color-picker for Xorg. It prompts the user to
select a pixel on their screen and will print the color
of said pixel, accordingly.

By default,
.B xcol
prints the result in decimal.
.SH OPTIONS
.TP
.BR \-h
Returns the output in hexadecimal.
.SH BUGS
None known.
.SH LICENSE
See LICNSE, included with this repository.
.SH AUTHOR
.EX
Natamo <madstk1@pm.me>
.EE
.SH HOMEPAGE
.EX
https://github.com/madstk1/xcol
.EE
